netty:
  default:
    allocator:
      max-order: 3
micronaut:
  router:
    static-resources:
      default:
        paths: classpath:public
        mapping: /**
        enabled: true
  server:
    netty:
      responses:
        file:
          cache-control:
            public: true
  http:
    client:
      read-timeout: 40s

palm:
  PROJECT_ID: genai-java-demos
  CLOUD_REGION: us-central1
  API_ENDPOINT: us-central1-aiplatform.googleapis.com
  MODEL_ID: text-bison-32k
